name: CI
on: []
jobs:
  build:
    name: Build, lint, and test on Node and macOS-latest

    runs-on: macOS-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node 12
        uses: actions/setup-node@v2

      - name: Build
        run: yarn build
